### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by LetsDoNothing**

### CODE REVIEW

**Comment by ilyassesalama** [comment]
For the material library, I already added a comment that you shouldn't upgrade it because it causes memory leaks, and for the SDK version, I will not upgrade it yet until it becomes mandatory since SDK 32 isn't stable yet. Your changes will not be accepted. Thanks.

**Comment by PranavPurwar** [comment]
sdk 32 is android 12 and Android 12 is already stable

**Comment by PranavPurwar** [comment]
Android 13 (api 33) is unstable

**Comment by ilyassesalama** [comment]
What, fr. I thought it's Android 13. My bad. But still not going to merge because of the material library change.

**Comment by LetsDoNothing** [comment]
Screenshot_2022-05-15-04-19-14-157_com android chrome
Material V 1.6.0 is a stable version and not cause memory leak .

**Pull request closed without merging**
